quazip/zip.c

warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
for (i=(int)uReadSize-3; (i--)>0;)

warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]

---

CMakeLists.txt

See https://github.com/macports/macports-ports/commit/98445d69fc13be9c968abe4c597de8324b0ceee6
for explanations.
Also, CMake documents clearly say that cmake_minimum_required should be the first command in top-level CMakeLists.txt. [1]
[1] https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html

Fix building with non-Apple Clang on macOS

---

quazip/JlCompress.cpp
quazip/quaziodevice.cpp
quazip/quazipdir.cpp
quazip/quazipfile.cpp
quazip/quazipnewinfo.cpp

Hi stachenov,
i added QStringLiteral and  QString::fromStdString to chars for people who use the defines like:
QT_NO_CAST_FROM_ASCII,
QT_NO_CAST_TO_ASCII,
QT_NO_URL_CAST_FROM_STRING,
Wihout QStringLiteral and QString::fromStdString the cant use this wonderfull library.
Alsow its a performace boost and safty feature.
Many greetings, isy

Added QStringLiteral and QString::fromStdString

---

qztest/testquazip.cpp

If int is bigger than quint16 then you will get the following
linker error:
.obj/testquazip.o: In function `TestQuaZip::setOsCode()':
testquazip.cpp:(.text+0x42bd): undefined reference to `bool QTest::qCompare<int, unsigned short>(int const&, unsigned short const&, char const*, char const*, char const*, int)'
collect2: error: ld returned 1 exit status
This error indicates the two parameters of QCOMPARE do not have the same type.
This occurs because integral promotions can be applied to fi.versionCreated.

fix qztest build error.

---

quazip/quagzipfile.cpp
quazip/quaziodevice.cpp
quazip/quazip.pro
quazip/quazipdir.cpp
quazip/quazipnewinfo.cpp
quazip/quazipnewinfo.h
qztest/qztest.pro
qztest/testjlcompress.cpp
qztest/testquazip.cpp
qztest/testquazipfileinfo.cpp
qztest/testquazipnewinfo.cpp

trUtf8 is deprecated in Qt 5.0
qSort is deprecated in Qt 5.2
QFileInfo::created() is deprecated in Qt 5.10
Changes as discussed in PR #22
This PR also makes the changes to the qztest project

Fix Qt5 deprecated warnings

---

quazip/quazipfileinfo.cpp

redundant trailing `>` removed

Fix typo (compilation fails on this typo)

---

quazip/JlCompress.cpp
quazip/JlCompress.h
quazip/qioapi.cpp
quazip/quaadler32.h
quazip/quachecksum32.h
quazip/quagzipfile.cpp
quazip/quagzipfile.h
quazip/quaziodevice.cpp
quazip/quaziodevice.h
quazip/quazip.cpp
quazip/quazip.h
quazip/quazipdir.cpp
quazip/quazipdir.h
quazip/quazipfile.h
quazip/quazipfileinfo.cpp
quazip/quazipfileinfo.h
quazip/quazipnewinfo.cpp
quazip/quazipnewinfo.h

Allow using other compilers / IDEs that are not qmake / QtDesigner to use this without adding an additional include directory.
Qt's own moc also generates includes with <module/file>.

Fix includes to include QtCore/

---

quazip/JlCompress.cpp

`NoFilters` flag is `-1`, not a zero.  And does not change when is `|`-ed on line 104. 
The problem is caused by `NoFilters`, that is handled as a special case in `entryInfoList()` and results to ignoring NoDotAndNoDotDot, that in turn  lead to infinite loop on '.' file.

Fix infinite recursion after unsafe change

---

quazip/JlCompress.h
quazip/quazip.h

In Qt 6 QTextCodec is removed from Core into a Qt 5 Compat module, it's the only removed class that is in use. This fixes the include so it compiles with Qt 6 using the Qt 5 Compat module.
I see there is already work with CMake that probably will conflict with Qt 6 CMake changes so I'm waiting with that.
All that needs to be added is:
option(BUILD_WITH_QT6 "Compile with Qt 6")
Then do:
`find_package(Qt6 COMPONENTS Core Core5Compat)`
Add a section for if(Qt6Core_FOUND)
`set(QTCORE_LIBRARIES Qt6::Core Qt6::Core5Compat)`
and change qt5_wrap_cpp to qt6_wrap_cpp
etc.

Fix compile with Qt 6

---

CMakeLists.txt

QuaZip also supports Qt6, which was missing in the doc-string of
cache variable `${QUAZIP_QT_MAJOR_VERSION}`

CMake: Fix doc-string for `${QUAZIP_QT_MAJOR_VERSION}`

---

CMakeLists.txt
quazip/doc/index.dox

Currently, the default value of `${QUAZIP_QT_MAJOR_VERSION}` is hard-
coded to 5.  If users want to use this package, they have to explicitly
set this variable, e.g. through `cmake .. -DQUAZIP_QT_MAJOR_VERSION=6`.
It would be better to detect the Qt version, that is installed on the
users system, and use that as the default.  This commit does exactly
that:
We search for either Qt6, Qt5 or Qt4 (in that order). If none is found,
we exit directly at that point.  If found, the major version is stored
in `${QT_VERSION_MAJOR}` which we subsequently use as the default value
for `${QUAZIP_QT_MAJOR_VERSION}`.
__Examples__:
No Qt installed:
`cmake -S .. -B .`
```
CMake Error at CMakeLists.txt:16 (find_package):
Could not find a package configuration file provided by "QT" with any of
the following …
```

CMake: Set default of `${QUAZIP_QT_MAJOR_VERSION}` to the Qt found

---

quazip/JlCompress.cpp
quazip/JlCompress.h

[PolyMC](https://github.com/PolyMC/PolyMC) (and [MultiMC](https://github.com/MultiMC/Launcher)) use a modified version of QuaZip currently. I am currently working on removing old cruft like this. We utilize a few private methods of `JlCompress`, which are public in the modified version of QuaZip. I don't really see an issue in making it public here in upstream as well.

Expose all JlCompress methods

---

quazip/JlCompress.cpp

[QT_NO_CAST_FROM_ASCII ](https://doc.qt.io/qt-6/qstring.html#QT_NO_CAST_FROM_ASCII) is used to prevent occasional bugs with implicit conversion.

Fix build with  QT_NO_CAST_FROM_ASCII defined

---

quazip/QuaZipConfig.cmake.in

> https://github.com/stachenov/quazip/issues/121
```
links to target "Qt5::Zlib" but the target was not found
```
this should be fixed properly

use QtXZlib in config.cmake if specified

---

CMakeLists.txt

They appear to have a hard time deciding what to name the poor thing, but this will make sure it builds with Qt6.6.1+.

The internal Zlib module name changed again in Qt6.6

---

quazip/quaziodevice.cpp

Zlib supports ZLIB_CONST definition which enables const qualifier for input pointers, but currently this definition breaks QuaZip compilation.

Fix compilation when ZLIB_CONST defined

---

.github/workflows/zlib-ng.yml
qztest/testjlcompress.cpp

zlib-ng is used by default on some distros like Fedora. It is ABI compatible with zlib but produces different final zip content. Introduce additional hashes in tests to cover this case.

Fix test hashes when using zlib-ng

---

quazip/quazip_qt_compat.h

Fixes #228 
This PR was tested on the following systems:
- Windows
- Linux (Ubuntu and Arch)
- Linux (Ubuntu) to emscripten
- Linux (Ubuntu) to android.

Fixed builds for emscripten on qt 6.8 +

---

quazip/ioapi.h
quazip/minizip_crypt.h
quazip/quagzipfile.cpp
quazip/quaziodevice.cpp
quazip/quazip.cpp
quazip/quazipdir.cpp
quazip/quazipdir.h
quazip/quazipfile.cpp
quazip/quazipnewinfo.cpp
quazip/unzip.c
quazip/zip.c

Closes #230 
still needs some more work

[build] Fix shadow and missing-decl errors

---

.github/workflows/ci.yml

macos-13 is deprecated in December, move to 14 and 15.

Refresh macos workers
